language: generic

services:
  - docker

before_install:
  - echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USER" --password-stdin
  - docker build -t rawdata .

script:
  - docker run rawdata /rawdata/run_tests.sh

